// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnritBcjgk2yWjteD_nKmndtpyVcVXWLw',
    appId: '1:992961158660:web:d543fb1e2839a98f875f51',
    messagingSenderId: '992961158660',
    projectId: 'home-fix-ai-5429f',
    authDomain: 'home-fix-ai-5429f.firebaseapp.com',
    storageBucket: 'home-fix-ai-5429f.firebasestorage.app',
    measurementId: 'G-QKHJVPR1X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxP2Iy-mqpz5CtQNrZrghH5I8xqadsB-c',
    appId: '1:992961158660:android:b18a6e709176b643875f51',
    messagingSenderId: '992961158660',
    projectId: 'home-fix-ai-5429f',
    storageBucket: 'home-fix-ai-5429f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi_oL6flgT-D9voM2ZTg9UaSO-S06kPps',
    appId: '1:519882857957:ios:2adbcf2889c5c01761230c',
    messagingSenderId: '519882857957',
    projectId: 'home-fix-ai-demo-de038',
    storageBucket: 'home-fix-ai-demo-de038.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi_oL6flgT-D9voM2ZTg9UaSO-S06kPps',
    appId: '1:519882857957:ios:2adbcf2889c5c01761230c',
    messagingSenderId: '519882857957',
    projectId: 'home-fix-ai-demo-de038',
    storageBucket: 'home-fix-ai-demo-de038.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnritBcjgk2yWjteD_nKmndtpyVcVXWLw',
    appId: '1:992961158660:web:3157c18220018413875f51',
    messagingSenderId: '992961158660',
    projectId: 'home-fix-ai-5429f',
    authDomain: 'home-fix-ai-5429f.firebaseapp.com',
    storageBucket: 'home-fix-ai-5429f.firebasestorage.app',
    measurementId: 'G-K6S8MMGYR7',
  );
}
